BEGIN;

CREATE TABLE behaviors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id INTEGER NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(200) NOT NULL,
    code TEXT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_behaviors_club_name UNIQUE (club_id, name),
    CONSTRAINT uq_behaviors_club_id_id UNIQUE (club_id, id)
);

CREATE TABLE players (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id INTEGER NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    behavior_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    power INTEGER NOT NULL,
    agility INTEGER NOT NULL,
    control INTEGER NOT NULL,
    speed INTEGER NOT NULL,
    strength INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_players_behavior_club
        FOREIGN KEY (club_id, behavior_id)
        REFERENCES behaviors(club_id, id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_players_power CHECK (power BETWEEN 20 AND 100),
    CONSTRAINT ck_players_agility CHECK (agility BETWEEN 20 AND 100),
    CONSTRAINT ck_players_control CHECK (control BETWEEN 20 AND 100),
    CONSTRAINT ck_players_speed CHECK (speed BETWEEN 20 AND 100),
    CONSTRAINT ck_players_strength CHECK (strength BETWEEN 20 AND 100),
    CONSTRAINT ck_players_pacss_total
        CHECK (power + agility + control + speed + strength = 300)
);

CREATE INDEX ix_behaviors_club_id ON behaviors(club_id);
CREATE INDEX ix_players_club_id ON players(club_id);


COMMIT;