BEGIN;

CREATE TABLE leagues (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    min_teams INTEGER NOT NULL,
    max_teams INTEGER NOT NULL,
    start_datetime TIMESTAMPTZ NOT NULL,
    round_interval VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'open'
);

CREATE TABLE league_registrations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id INTEGER NOT NULL 
        REFERENCES leagues(id) ON DELETE CASCADE,
    club_id INTEGER NOT NULL 
        REFERENCES clubs(id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_league_registrations_league_club UNIQUE (league_id, club_id)
);

CREATE INDEX ix_league_registrations_league_id ON league_registrations(league_id);
CREATE INDEX ix_league_registrations_club_id ON league_registrations(club_id);

COMMIT;