BEGIN;
CREATE TABLE friendly_matches(
    match_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id  INTEGER NOT NULL
            REFERENCES clubs(id) ON DELETE CASCADE,
    visitor_id  INTEGER NULL
            REFERENCES clubs(id) ON DELETE CASCADE,
    init_date   TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_matches_local ON friendly_matches(creator_id);
CREATE INDEX ix_matches_visitor ON friendly_matches(visitor_id);

COMMIT;